# -*- coding: utf-8 -*-
"""AND_OR_GATES.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T4F2syswDgXiNKTiUDEcs_g-VtHlqfat
"""

import numpy as np
import pandas as pd

x1 = [0,1]
x2 = [[0,0],[0,1],[1,0],[1,1]]

gates = {}
gates['X'] = x2

"""**FUNCTIONS**"""

def activation(y_hat):
    if(y_hat>=0):
        return 1
    else:
        return 0

def perceptron(x,w,b):
    y = []
    for x_hat in x:
        # print(x_hat)
        xw = np.dot(x_hat,w) + b
        # print(xw)
        y.append(activation(xw))
    return y



"""**AND GATE**"""

def AND(x):
    w = [1,1]
    b = -2
    # print(x)
    return perceptron(x,w,b)

and_ = AND(x2)
gates['AND'] = and_
print('AND', and_)

all_w = [[0,0],[0,1],[1,0],[1,1]]
all_b = [-2, -1, 0, 1, 2]

for w in all_w:
    for b in all_b:
        temp = perceptron(x2,w,b)
        if temp == and_:
            print(w, b, temp)

data = pd.DataFrame(gates)
print(data)



"""**OR GATE**"""

def OR(x):
    w = [1,1]
    b = -1
    # print(x)
    return perceptron(x,w,b)

or_ = OR(x2)
gates['OR'] = or_
print('OR', or_)

all_w = [[0,0],[0,1],[1,0],[1,1]]
all_b = [-1, -2, 0, 1, 2]

for w in all_w:
    for b in all_b:
        temp = perceptron(x2,w,b)
        if temp == or_:
            print(w, b, temp)

data = pd.DataFrame(gates)
print(data)

