# -*- coding: utf-8 -*-
"""MOMENTUM_GRADIENT_dESCENT_STOCHASTIC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1axR4igd_uStELUKp0S0TY9J6pbAbx62Z
"""

import numpy as np
import pandas as pd
from sklearn import datasets
import matplotlib.pyplot as plt

def sigmoid(Y_in):
    return 1 / (1 + np.exp(-Y_in))

def find_Yhat(X, w, b):
    # IF LIST OF LIST / LIST OF TUPLE IS USED, THEN INDIVIDUAL LIST/TUPLE SHOULD BE HANDLED DIFFERENTLY
    if type(X) in [type([1]), type((1,2))]:
        Y_in = np.dot(X, w) + b
    else:
        Y_in = X * w + b

    return sigmoid(Y_in)

def delta_w(X, Y_true, Y_pred):
  return -2 * (Y_true - Y_pred) * Y_pred * (1 - Y_pred) * X

def delta_b(Y_true, Y_pred):
  return -2 * (Y_true - Y_pred) * Y_pred * (1 - Y_pred)

X = [0.5, 2.5]
Y = [0.2, 0.9]

n_epochs = 300
df = pd.DataFrame([(x, y) for x, y in zip(X, Y)], columns = ['X', 'Y'])
df.head()

"""sgd_m

"""

def sgd_momentum(X, Y, noofepochs = 300, beta = 0.5):
    w = -2; alpha = 1; b = -2;

    # LIST FOR ALL EPOCHS
    error_mega_list = []
    weights_mega_list = []
    bias_mega_list = []
        
    for i in range(noofepochs):
        # LIST FOR EACH EPOCH
        error_list = []

        # HISTORY IS PER EPOCH, SO UPDATING AFTER EVERY EPOCH
        vw, vb = 0, 0

        for x, y in zip(X, Y):
            Y_hat = find_Yhat(x, w, b)
            error_list.append((y - Y_hat) ** 2)

            dw = delta_w(x, y, Y_hat)
            db = delta_b(y, Y_hat)

            vw = beta * vw + (1 - beta) * dw
            vb = beta * vb + (1 - beta) * db
            w += (-alpha * vw)
            b += (-alpha * vb)
        
        error_mega_list.append(error_list)
        weights_mega_list.append(w)
        bias_mega_list.append(b)
        
    return error_mega_list, weights_mega_list, bias_mega_list

errors_sgdM, weights_sgdM, biases_sgdM = sgd_momentum(X, Y, n_epochs)

print(round(np.mean(errors_sgdM[-1]),5))
print(round(weights_sgdM[-1],3))
print(round(biases_sgdM[-1],3))

plt.title("WEIGHT VS EPOCHS")
epoch_range = [i for i in range(n_epochs)]
weight_range = [w for w in weights_sgdM]
plt.plot(epoch_range, weight_range)
plt.xlabel('EPOCHS ')
plt.ylabel('WEIGHT')
plt.show()

plt.title("WEIGHT VS EPOCHS")
epoch_range = [i for i in range(n_epochs)]
weight_range = [w for w in biases_sgdM]
plt.plot(epoch_range, weight_range)
plt.xlabel('EPOCHS ')
plt.ylabel('WEIGHT')
plt.show()

plt.title("WEIGHT VS EPOCHS")
#epoch_range = [i for i in range(n_epochs)]
weight_range = [w for w in errors_sgdM]
plt.plot( weight_range)
#plt.xlabel('EPOCHS ')
#plt.ylabel('errors')
plt.show()

