# -*- coding: utf-8 -*-
"""NOT_GATE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16qV5tEqFcqiNJTnosN48qStgYP17yVBJ
"""



import numpy as np
import pandas as pd

x1 = [0,1]
x2 = [[0,0],[0,1],[1,0],[1,1]]

gates = {}
gates['X'] = x2

"""**FUNCTIONS**"""

def activation(y_hat):
    if(y_hat>=0):
        return 1
    else:
        return 0

def perceptron(x,w,b):
    y = []
    for x_hat in x:
        # print(x_hat)
        xw = np.dot(x_hat,w) + b
        # print(xw)
        y.append(activation(xw))
    return y

"""**NOT GATE**"""

def NOT(x):
    w = [-1]
    b = 0
    # print(x)
    return perceptron(x,w,b)

not_ = NOT(x1)
print('NOT', not_)

all_w = [1,0]
all_b = [-1, 0, 1,]

for w in all_w:
    for b in all_b:
        temp = perceptron(x1,w,b)
        
        
        if(temp == not_):
            print(w, b, temp)

not_gate = {'X': x1, 'NOT': not_}
data = pd.DataFrame(not_gate)
print(data)

